// The runtime version is this fingerprint (app.config.js -> runtimeVersion),
// and the deploy workflow (.eas/workflows/deploy-production.yml) uses it to
// choose between an OTA update and a store build. A native change the
// fingerprint misses ships as an OTA update and never reaches users.
/** @type {import('expo/fingerprint').Config} */
module.exports = {
  // The widget's Swift sources are compiled by @bacons/apple-targets, but
  // fingerprint only sees the target's expo-target.config.js -- without this,
  // editing JourneyWidget.swift would not trigger a new build.
  extraSources: [
    { type: "dir", filePath: "targets", reasons: ["appleTargets"] },
  ],
  // ios/ and android/ are generated by prebuild and gitignored, so EAS never
  // has them. Hashing a local copy would only make local and CI fingerprints
  // disagree. Same for the local module's Gradle output.
  ignorePaths: [
    "ios/**/*",
    "android/**/*",
    "modules/live-journey/android/build/**/*",
  ],
};
